// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism.Data;

#nullable disable

namespace Tourism.Data.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327193015_AddCategoryPaymentContact")]
    partial class AddCategoryPaymentContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore ancient ruins, museums, and the stories behind the world's greatest civilisations.",
                            IconClass = "bi-bank",
                            Name = "Cultural & Historical"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sun, sea, and sand — the finest coastal and island escapes in Europe.",
                            IconClass = "bi-water",
                            Name = "Beach & Island"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact, action-packed getaways to Europe's most vibrant and charming cities.",
                            IconClass = "bi-buildings",
                            Name = "City Break"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Multi-destination road trips, trekking routes, and experiences off the beaten path.",
                            IconClass = "bi-compass",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Premium hotels, skip-the-line access, private guides, and unforgettable fine dining.",
                            IconClass = "bi-stars",
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kid-friendly itineraries designed to create memories for the whole family.",
                            IconClass = "bi-people",
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Italy",
                            Description = "The Eternal City with thousands of years of history — the Colosseum, the Vatican, and world-renowned Italian cuisine.",
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 2,
                            Country = "France",
                            Description = "The City of Love — the Eiffel Tower, the Louvre, and an unforgettable romantic atmosphere.",
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Spain",
                            Description = "A sun-drenched coastal city with Gaudí's iconic architecture, vibrant Las Ramblas, and beautiful beaches.",
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Croatia",
                            Description = "The Pearl of the Adriatic — medieval walls, crystal-clear sea, and picturesque cobblestone streets.",
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
                            Name = "Dubrovnik"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Greece",
                            Description = "The cradle of civilization — the Acropolis, the Parthenon, and rich Mediterranean cuisine.",
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Czech Republic",
                            Description = "The City of a Hundred Spires — fairy-tale medieval architecture, Charles Bridge, and a bohemian atmosphere.",
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80",
                            Name = "Prague"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Turkey",
                            Description = "The bridge between Europe and Asia — Hagia Sophia, the Grand Bazaar, and the flavors of the Orient.",
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Netherlands",
                            Description = "The City of Canals — bicycles, tulips, world-class museums, and unique Dutch architecture.",
                            ImageUrl = "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Austria",
                            Description = "The Imperial City — grand palaces, opera houses, famous Viennese cafés, and classical music.",
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Greece",
                            Description = "A volcanic island with whitewashed buildings, blue domes, and some of the most beautiful sunsets in the world.",
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
                            Name = "Santorini"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Portugal",
                            Description = "A city of seven hills — historic trams, Fado music, Moorish castles, and the world's finest custard tarts.",
                            ImageUrl = "https://images.unsplash.com/photo-1558370781-d6196949e317?w=800&q=80",
                            Name = "Lisbon"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Hungary",
                            Description = "The Pearl of the Danube — grand thermal baths, stunning Parliament, ruin bars, and a vibrant nightlife scene.",
                            ImageUrl = "https://images.unsplash.com/photo-1541343672885-9be56236302a?w=800&q=80",
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Greece",
                            Description = "The jewel of the Cyclades — windmills, whitewashed alleys, vibrant beach clubs, and crystal-clear Aegean waters.",
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80",
                            Name = "Mykonos"
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.FavoriteTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId", "TourId")
                        .IsUnique();

                    b.ToTable("FavoriteTours");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPerson")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourOperatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TourOperatorId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A 5-day journey to the Eternal City. Visit the Colosseum, the Roman Forum, the Vatican, and toss a coin in the Trevi Fountain. Includes expert guide, 4* hotel, and breakfast.",
                            DestinationId = 1,
                            DiscountPercent = 0m,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 899m,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Classic Rome",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An exclusive 3-day weekend tour with skip-the-line entry to the Vatican Museums, a private dinner in Trastevere, and nights in a boutique hotel in the heart of Rome.",
                            DestinationId = 1,
                            DiscountPercent = 0m,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=800&q=80",
                            MaxParticipants = 10,
                            PricePerPerson = 1250m,
                            StartDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rome & Vatican — VIP Tour",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 days in the City of Light — the Eiffel Tower, the Louvre, Montmartre, and a cruise along the Seine. Perfect for couples and art lovers.",
                            DestinationId = 2,
                            DiscountPercent = 0m,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
                            MaxParticipants = 15,
                            PricePerPerson = 1199m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Romantic Paris",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A short 3-day Paris weekend — ideal for those with limited time off. Flights, hotel, and all major highlights included.",
                            DestinationId = 2,
                            DiscountPercent = 0m,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 649m,
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Paris Weekend",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the magic of Barcelona with visits to the Sagrada Família, Park Güell, Casa Batlló, and the vibrant Boqueria market.",
                            DestinationId = 3,
                            DiscountPercent = 0m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
                            MaxParticipants = 25,
                            PricePerPerson = 799m,
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barcelona & Gaudí",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 days in Dubrovnik and along the Croatian coast. Walk the ancient city walls, take a day trip to Lokrum Island, and relax on the beaches of Budva.",
                            DestinationId = 4,
                            DiscountPercent = 0m,
                            DurationDays = 6,
                            EndDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
                            MaxParticipants = 18,
                            PricePerPerson = 699m,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Adriatic Pearl",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Immerse yourself in the history of Ancient Greece — the Acropolis, the National Museum, the Monastiraki district, and a traditional Greek dinner with live music.",
                            DestinationId = 5,
                            DiscountPercent = 0m,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
                            MaxParticipants = 22,
                            PricePerPerson = 649m,
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Athens Adventure",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 days in fairy-tale Prague — Charles Bridge, Prague Castle, the Old Town Square, and legendary Czech beers in historic pubs.",
                            DestinationId = 6,
                            DiscountPercent = 0m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80",
                            MaxParticipants = 30,
                            PricePerPerson = 549m,
                            StartDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Magic of Prague",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A combined tour to two of Europe's most beautiful imperial capitals — 4 days in Prague and 4 days in Vienna, with coach transfer and 3* hotels.",
                            DestinationId = 6,
                            DiscountPercent = 0m,
                            DurationDays = 8,
                            EndDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80",
                            MaxParticipants = 25,
                            PricePerPerson = 980m,
                            StartDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prague & Vienna — 8 Days",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 unforgettable days in Istanbul — Hagia Sophia, the Blue Mosque, the Grand Bazaar, a Bosphorus cruise, and an authentic Turkish dinner with folk dancers.",
                            DestinationId = 7,
                            DiscountPercent = 0m,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 729m,
                            StartDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Istanbul — Bridge of Worlds",
                            TourOperatorId = 4
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A 4-day tour with a canal cruise, visits to the Van Gogh Museum and Rijksmuseum, a bicycle ride through the city, and a flower market.",
                            DestinationId = 8,
                            DiscountPercent = 0m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
                            MaxParticipants = 18,
                            PricePerPerson = 819m,
                            StartDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Amsterdam — City of Canals",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 days in the Habsburg capital — Schönbrunn Palace, the State Opera, Belvedere, Viennese cafés, and a classical music concert.",
                            DestinationId = 9,
                            DiscountPercent = 0m,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 899m,
                            StartDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Imperial Vienna",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 days on the volcanic island of Santorini — sunsets from Oia, volcanic beaches, local wine tasting, and a cruise around the island.",
                            DestinationId = 10,
                            DiscountPercent = 0m,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
                            MaxParticipants = 14,
                            PricePerPerson = 1399m,
                            StartDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Santorini — Island of Dreams",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A 3-day weekend flight to Santorini — nights in a traditional Cycladic villa overlooking the caldera, and a private yacht tour.",
                            DestinationId = 10,
                            DiscountPercent = 0m,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
                            MaxParticipants = 8,
                            PricePerPerson = 850m,
                            StartDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Santorini Weekend",
                            TourOperatorId = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An epic 10-day tour across the Balkans — Athens, Thessaloniki, Ohrid, and Budva. A blend of history, nature, and authentic Balkan cuisine.",
                            DestinationId = 5,
                            DiscountPercent = 0m,
                            DurationDays = 10,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1590147534648-1ac5cca59621?w=800&q=80",
                            MaxParticipants = 28,
                            PricePerPerson = 1100m,
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Balkan Express — 10 Days",
                            TourOperatorId = 5
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 magical days in Lisbon — ride the iconic Tram 28 through Alfama, explore Belém Tower, taste pastel de nata in historic cafés, and watch the sun set over the Tagus river.",
                            DestinationId = 11,
                            DiscountPercent = 10m,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1558370781-d6196949e317?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 749m,
                            StartDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lisbon Highlights",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A 7-day journey through Portugal's two most beloved cities — cobblestone Lisbon and the port wine cellars of Porto, with a day trip to Sintra's fairy-tale palaces.",
                            DestinationId = 11,
                            DiscountPercent = 0m,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
                            MaxParticipants = 18,
                            PricePerPerson = 999m,
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lisbon & Porto — Atlantic Coast",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 days in one of Europe's most breathtaking capitals — Buda Castle, the Parliament building, a relaxing soak in Széchenyi Baths, and an evening cruise on the glittering Danube.",
                            DestinationId = 12,
                            DiscountPercent = 0m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1541343672885-9be56236302a?w=800&q=80",
                            MaxParticipants = 22,
                            PricePerPerson = 649m,
                            StartDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Budapest Royal",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 days combining the grandeur of Budapest with a relaxing escape to Lake Balaton — Central Europe's largest lake. Wine tastings, spa villages, and stunning lakeside sunsets included.",
                            DestinationId = 12,
                            DiscountPercent = 12m,
                            DurationDays = 6,
                            EndDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1549555340-9f9e3b0c5b0e?w=800&q=80",
                            MaxParticipants = 16,
                            PricePerPerson = 849m,
                            StartDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Budapest & Lake Balaton",
                            TourOperatorId = 5
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 sun-soaked days on the most glamorous island in the Cyclades — party beaches, windmill sunsets, fresh seafood by the water, and day trips to the sacred island of Delos.",
                            DestinationId = 13,
                            DiscountPercent = 0m,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80",
                            MaxParticipants = 12,
                            PricePerPerson = 1299m,
                            StartDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mykonos Escape",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ultimate Greek island experience — 4 nights on vibrant Mykonos followed by 4 nights on dreamy Santorini. Ferry included, boutique hotel, private sunset tour.",
                            DestinationId = 13,
                            DiscountPercent = 8m,
                            DurationDays = 8,
                            EndDate = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
                            MaxParticipants = 10,
                            PricePerPerson = 1799m,
                            StartDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mykonos & Santorini — Island Duo",
                            TourOperatorId = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "See all the must-see sights of Rome without breaking the bank — Colosseum, Pantheon, Piazza Navona, and the Vatican, with comfortable 3* accommodation and daily breakfast.",
                            DestinationId = 1,
                            DiscountPercent = 20m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80",
                            MaxParticipants = 30,
                            PricePerPerson = 549m,
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rome Budget Explorer",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An epic 10-day island-hopping adventure — Athens, Mykonos, Paros, and Santorini. Ferry passes, guided excursions, and handpicked boutique hotels all included.",
                            DestinationId = 5,
                            DiscountPercent = 0m,
                            DurationDays = 10,
                            EndDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80",
                            MaxParticipants = 14,
                            PricePerPerson = 1599m,
                            StartDate = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greek Island Hopping",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "8 days across the Iberian Peninsula — Barcelona, Madrid, Seville, and Lisbon. High-speed trains, flamenco show, wine tasting, and a blend of Moorish and modern Europe.",
                            DestinationId = 3,
                            DiscountPercent = 0m,
                            DurationDays = 8,
                            EndDate = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 1249m,
                            StartDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spain & Portugal — Iberian Grand Tour",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience Prague in its most enchanting season — Christmas markets, steaming mulled wine, snow-covered rooftops, and the Old Town Square glowing in festive lights.",
                            DestinationId = 6,
                            DiscountPercent = 15m,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80",
                            MaxParticipants = 30,
                            PricePerPerson = 499m,
                            StartDate = new DateTime(2026, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Winter Magic in Prague",
                            TourOperatorId = 3
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1571366343168-631c5bcca7a4?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd411b5?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1490644658840-3f2e3f8c5625?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1541171418693-a55571e5c25f?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 5
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://images.unsplash.com/photo-1561518776-e76a5e48f731?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 6
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://images.unsplash.com/photo-1600240644455-3edc55c375fe?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 6
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://images.unsplash.com/photo-1548625149-720834e8fa96?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 7
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 7
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 7
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://images.unsplash.com/photo-1541726260-e6b6a6a1b27e?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 8
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 8
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://images.unsplash.com/photo-1592906209472-a36b1f3782ef?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 8
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 9
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 9
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 9
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 10
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 10
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 10
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 10
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 11
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 11
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "https://images.unsplash.com/photo-1576924542622-772281b13e94?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 11
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 12
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 12
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 12
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "https://images.unsplash.com/photo-1609767791926-c9e2e7ca33ac?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 12
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 13
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 13
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 13
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1200&q=80",
                            SortOrder = 4,
                            TourId = 13
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 14
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 14
                        },
                        new
                        {
                            Id = 49,
                            ImageUrl = "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 14
                        },
                        new
                        {
                            Id = 50,
                            ImageUrl = "https://images.unsplash.com/photo-1590147534648-1ac5cca59621?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 15
                        },
                        new
                        {
                            Id = 51,
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 15
                        },
                        new
                        {
                            Id = 52,
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 15
                        },
                        new
                        {
                            Id = 53,
                            ImageUrl = "https://images.unsplash.com/photo-1558370781-d6196949e317?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 16
                        },
                        new
                        {
                            Id = 54,
                            ImageUrl = "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 16
                        },
                        new
                        {
                            Id = 55,
                            ImageUrl = "https://images.unsplash.com/photo-1513735492246-483525079686?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 16
                        },
                        new
                        {
                            Id = 56,
                            ImageUrl = "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 17
                        },
                        new
                        {
                            Id = 57,
                            ImageUrl = "https://images.unsplash.com/photo-1558370781-d6196949e317?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 17
                        },
                        new
                        {
                            Id = 58,
                            ImageUrl = "https://images.unsplash.com/photo-1513735492246-483525079686?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 17
                        },
                        new
                        {
                            Id = 59,
                            ImageUrl = "https://images.unsplash.com/photo-1541343672885-9be56236302a?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 18
                        },
                        new
                        {
                            Id = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 18
                        },
                        new
                        {
                            Id = 61,
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 18
                        },
                        new
                        {
                            Id = 62,
                            ImageUrl = "https://images.unsplash.com/photo-1541343672885-9be56236302a?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 19
                        },
                        new
                        {
                            Id = 63,
                            ImageUrl = "https://images.unsplash.com/photo-1549555340-9f9e3b0c5b0e?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 19
                        },
                        new
                        {
                            Id = 64,
                            ImageUrl = "https://images.unsplash.com/photo-1516496636080-14fb876e029d?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 19
                        },
                        new
                        {
                            Id = 65,
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 20
                        },
                        new
                        {
                            Id = 66,
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 20
                        },
                        new
                        {
                            Id = 67,
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 20
                        },
                        new
                        {
                            Id = 68,
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 21
                        },
                        new
                        {
                            Id = 69,
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 21
                        },
                        new
                        {
                            Id = 70,
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 21
                        },
                        new
                        {
                            Id = 71,
                            ImageUrl = "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 22
                        },
                        new
                        {
                            Id = 72,
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 22
                        },
                        new
                        {
                            Id = 73,
                            ImageUrl = "https://images.unsplash.com/photo-1571366343168-631c5bcca7a4?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 22
                        },
                        new
                        {
                            Id = 74,
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 23
                        },
                        new
                        {
                            Id = 75,
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 23
                        },
                        new
                        {
                            Id = 76,
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 23
                        },
                        new
                        {
                            Id = 77,
                            ImageUrl = "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 24
                        },
                        new
                        {
                            Id = 78,
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 24
                        },
                        new
                        {
                            Id = 79,
                            ImageUrl = "https://images.unsplash.com/photo-1558370781-d6196949e317?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 24
                        },
                        new
                        {
                            Id = 80,
                            ImageUrl = "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=80",
                            SortOrder = 1,
                            TourId = 25
                        },
                        new
                        {
                            Id = 81,
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80",
                            SortOrder = 2,
                            TourId = 25
                        },
                        new
                        {
                            Id = 82,
                            ImageUrl = "https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80",
                            SortOrder = 3,
                            TourId = 25
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TourOperators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A leading travel agency with over 20 years of experience organizing group and individual tours.",
                            Email = "info@balkantravel.bg",
                            LogoUrl = "",
                            Name = "Balkan Travel",
                            PhoneNumber = "+359 2 123 4567"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Specialists in Mediterranean and island tourism — sea, sun, and unforgettable experiences.",
                            Email = "contact@suntourism.bg",
                            LogoUrl = "",
                            Name = "Sun Tourism",
                            PhoneNumber = "+359 2 987 6543"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Group and individual tours to all European destinations with local expert guides.",
                            Email = "hello@europaexplorer.bg",
                            LogoUrl = "",
                            Name = "Europa Explorer",
                            PhoneNumber = "+359 2 555 1234"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2017, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exotic destinations, crossroads routes, and unforgettable adventures across Asia and the Middle East.",
                            Email = "orient@orienttours.bg",
                            LogoUrl = "",
                            Name = "Orient Tours",
                            PhoneNumber = "+359 2 444 5678"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Specialists in mountain and adventure tourism — trekking, skiing, and eco-travel.",
                            Email = "info@alpinepaths.bg",
                            LogoUrl = "",
                            Name = "Alpine Paths",
                            PhoneNumber = "+359 2 777 9900"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Booking", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.FavoriteTour", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Payment", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Review", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Category", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.TourOperator", "TourOperator")
                        .WithMany("Tours")
                        .HasForeignKey("TourOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");

                    b.Navigation("TourOperator");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourImage", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourOperator", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Category", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourOperator", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
