// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism.Data;

#nullable disable

namespace Tourism.Data.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309145544_FixBalkanImage")]
    partial class FixBalkanImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Италия",
                            Description = "Вечният град с хиляди години история — Колизеума, Ватикана и прочутата италианска кухня.",
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
                            Name = "Рим"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Франция",
                            Description = "Градът на любовта с Айфеловата кула, Лувъра и незабравимата романтична атмосфера.",
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
                            Name = "Париж"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Испания",
                            Description = "Слънчев крайбрежен град с архитектурата на Гауди, оживения Лас Рамблас и прекрасни плажове.",
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
                            Name = "Барселона"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Хърватия",
                            Description = "Перлата на Адриатика — средновековни стени, кристално синьо море и живописни улички.",
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
                            Name = "Дубровник"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Гърция",
                            Description = "Люлката на цивилизацията — Акрополът, Партенонът и богатата средиземноморска кухня.",
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
                            Name = "Атина"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Чехия",
                            Description = "Градът на сто кули — приказна средновековна архитектура, Карловият мост и бохемска атмосфера.",
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80",
                            Name = "Прага"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Турция",
                            Description = "Мостът между Европа и Азия — Света София, Гранд базарът и вкусовете на Ориента.",
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
                            Name = "Истанбул"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Нидерландия",
                            Description = "Градът на каналите — велосипеди, лалета, музеи и неповторима холандска архитектура.",
                            ImageUrl = "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
                            Name = "Амстердам"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Австрия",
                            Description = "Имперският град — дворци, опера, прочутите виенски кафенета и класическа музика.",
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
                            Name = "Виена"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Гърция",
                            Description = "Вулканичен остров с бели сгради, сини куполи и едни от най-красивите залези в света.",
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
                            Name = "Санторини"
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.FavoriteTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId", "TourId")
                        .IsUnique();

                    b.ToTable("FavoriteTours");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourOperatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TourOperatorId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5-дневно пътуване до Вечния град. Посетете Колизеума, Форума, Ватикана и хвърлете монета в Фонтана ди Треви. Включени са квалифициран водач, хотел 4* и закуски.",
                            DestinationId = 1,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 899m,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Класически Рим",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ексклузивен 3-дневен уикенд тур с влизане без опашка в Ватиканските музеи, частна вечеря в Трастевере и нощувки в бутиков хотел в центъра.",
                            DestinationId = 1,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1568797629192-789acf8e4df3?w=800&q=80",
                            MaxParticipants = 10,
                            PricePerPerson = 1250m,
                            StartDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Рим и Ватикана — VIP тур",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 дни в Града на светлините — Айфеловата кула, Лувъра, Монмартър и круиз по Сена. Перфектен за двойки и любители на изкуството.",
                            DestinationId = 2,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
                            MaxParticipants = 15,
                            PricePerPerson = 1199m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Романтичен Париж",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кратък 3-дневен уикенд в Париж — идеален за тези с малко отпуска. Самолет, хотел и основните забележителности включени.",
                            DestinationId = 2,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 649m,
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Париж Уикенд",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Открийте магията на Барселона с посещения на Саграда Фамилия, парк Гуел, Каса Батло и оживения пазар Бокерия.",
                            DestinationId = 3,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
                            MaxParticipants = 25,
                            PricePerPerson = 799m,
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Барселона и Гауди",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 дни в Дубровник и по хърватското крайбрежие. Разходка по крепостните стени, екскурзия до остров Локрум и плаж на Будва.",
                            DestinationId = 4,
                            DurationDays = 6,
                            EndDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=800&q=80",
                            MaxParticipants = 18,
                            PricePerPerson = 699m,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Адриатическа перла",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Потопете се в историята на Древна Гърция — Акропол, Националният музей, квартал Монастираки и вкусна гръцка вечеря с музика.",
                            DestinationId = 5,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
                            MaxParticipants = 22,
                            PricePerPerson = 649m,
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Атинско приключение",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4 дни в приказната Прага — Карловият мост, Пражкият замък, Старото градско ядро и легендарните чешки бири в исторически пивници.",
                            DestinationId = 6,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80",
                            MaxParticipants = 30,
                            PricePerPerson = 549m,
                            StartDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Магията на Прага",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Комбиниран тур до две от най-красивите имперски столици — 4 дни в Прага и 4 дни във Виена с автобусен преход и хотели 3*.",
                            DestinationId = 6,
                            DurationDays = 8,
                            EndDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555576208-f2598fdc0639?w=800&q=80",
                            MaxParticipants = 25,
                            PricePerPerson = 980m,
                            StartDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Прага и Виена — 8 дни",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 незабравими дни в Истанбул — Света София, Синята джамия, Гранд базарът, круиз по Босфора и автентична турска вечеря с танцьори.",
                            DestinationId = 7,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 729m,
                            StartDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Истанбул — Мостът на световете",
                            TourOperatorId = 4
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4-дневен тур с круиз по каналите, посещение на музея на Ван Гог и Рийксмузеум, разходка с велосипеди и пазар за цветя.",
                            DestinationId = 8,
                            DurationDays = 4,
                            EndDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
                            MaxParticipants = 18,
                            PricePerPerson = 819m,
                            StartDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Амстердам — Градът на каналите",
                            TourOperatorId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 дни в столицата на Хабсбургите — Дворецът Шьонбрун, Операта, Белведере, виенски кафенета и концерт с класическа музика.",
                            DestinationId = 9,
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80",
                            MaxParticipants = 20,
                            PricePerPerson = 899m,
                            StartDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Имперска Виена",
                            TourOperatorId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7 дни на вулканичния остров Санторини — залезите от Ия, вулканичните плажове, дегустация на местни вина и круиз около острова.",
                            DestinationId = 10,
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
                            MaxParticipants = 14,
                            PricePerPerson = 1399m,
                            StartDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Санторини — Остров на мечтите",
                            TourOperatorId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3-дневен уикенд полет до Санторини — нощувки в традиционна кикладска вила, гледка към калдерата и частна яхтена обиколка.",
                            DestinationId = 10,
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
                            MaxParticipants = 8,
                            PricePerPerson = 850m,
                            StartDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Санторини Уикенд",
                            TourOperatorId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Епичен 10-дневен тур из Балканите — Атина, Солун, Охрид и Будва. Смесица от история, природа и автентична балканска кухня.",
                            DestinationId = 5,
                            DurationDays = 10,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1590147534648-1ac5cca59621?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            MaxParticipants = 28,
                            PricePerPerson = 1100m,
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Балкански Експрес — 10 дни",
                            TourOperatorId = 5
                        });
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourOperators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Водеща туристическа агенция с над 20 години опит в организирането на групови и индивидуални пътувания.",
                            Email = "info@balkantravel.bg",
                            LogoUrl = "",
                            Name = "Балкан Травел",
                            PhoneNumber = "+359 2 123 4567"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Специалисти в средиземноморския и островен туризъм — море, слънце и незабравими преживявания.",
                            Email = "contact@suntourism.bg",
                            LogoUrl = "",
                            Name = "Сън Туризъм",
                            PhoneNumber = "+359 2 987 6543"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Групови и индивидуални пътувания до всички европейски дестинации с местни водачи.",
                            Email = "hello@europaexplorer.bg",
                            LogoUrl = "",
                            Name = "Европа Експлорър",
                            PhoneNumber = "+359 2 555 1234"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2017, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Екзотични дестинации, кръстопътни маршрути и незабравими приключения в Азия и Близкия изток.",
                            Email = "orient@orienttours.bg",
                            LogoUrl = "",
                            Name = "Ориент Турс",
                            PhoneNumber = "+359 2 444 5678"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Специалисти в планински и приключенски туризъм — трекинг, ски и еко пътувания.",
                            Email = "info@alpinepaths.bg",
                            LogoUrl = "",
                            Name = "Алпийски Преходи",
                            PhoneNumber = "+359 2 777 9900"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Booking", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.FavoriteTour", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Review", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.HasOne("Tourism.Data.Models.Entities.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tourism.Data.Models.Entities.TourOperator", "TourOperator")
                        .WithMany("Tours")
                        .HasForeignKey("TourOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TourOperator");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tourism.Data.Models.Entities.TourOperator", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
